services:
  web:
    build: .
    container_name: fern-website
    restart: unless-stopped
    env_file:
      - ".env"
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN
  